import Head from "next/head";
import Script from "next/script";
import { useEffect, useState } from "react";
import { debugPosition } from "../src/helper";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [renderAr, setRenderAr] = useState(false);

  useEffect(() => {
    debugPosition();
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>AR</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello</h1>

      {/* Couldn't get this working in the head element,
         using strategy and renderAr flag to ensure correct load order.
      */}
      <Script
        src="https://aframe.io/releases/1.0.4/aframe.min.js"
        strategy="beforeInteractive"
      />
      <Script
        src="https://unpkg.com/aframe-look-at-component@0.8.0/dist/aframe-look-at-component.min.js"
        strategy="beforeInteractive"
      />
      <Script
        src="https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar-nft.js"
        strategy="afterInteractive"
        onLoad={() => setRenderAr(true)}
      />

      {renderAr && (
        <a-scene
          vr-mode-ui="enabled: false"
          embedded
          arjs="sourceType: webcam; sourceWidth:1280; sourceHeight:960; displayWidth: 1280; displayHeight: 960; debugUIEnabled: true;"
        >
          <a-text
            value="This content will always face you."
            look-at="[gps-camera]"
            scale="120 120 120"
            gps-entity-place="latitude: <your position>; longitude: <your position>;"
          ></a-text>
          <a-camera gps-camera rotation-reader></a-camera>
        </a-scene>
      )}
    </div>
  );
}
